---
# tasks file for ansible-role-common
- name: Install Centos 7 EPEL
  yum: name="https://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm" state=present
  when: ansible_distribution_major_version == '7'
